#!/bin/sh

client="`dirname $0`/kappa.bin"

if [ -z "$DISPLAY" ]; then
    echo "Error: can't open display."
    echo "Please set DISPLAY variable"
    exit 1
fi

if [ ! -x "$client" ]; then
    echo "Error: can't execute $client."
    exit 1
fi

$client $*
while test $? -ne 0; do
    $client
done
exit 0

# while true; do
#    $client $*
#    if [ $? -eq 0 ]; then
#	exit 0
#    fi
#done
